/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * formula-interpreter API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export type DebugFeature = (typeof DebugFeature)[keyof typeof DebugFeature];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DebugFeature = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;
