/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * formula-interpreter API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { ElementExecution } from "./elementExecution";
import type { ParserExecutionProcessedIn } from "./parserExecutionProcessedIn";

export interface ExecutionResult {
  elementExecutions: ElementExecution[];
  exactProcessedInNanos: number;
  executedAtEnd: string;
  executedAtStart: string;
  parserExecutionProcessedIn?: ParserExecutionProcessedIn;
  result: string;
}
