/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * formula-interpreter API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { ElementExecution } from "./elementExecution";

export interface ExecutionResult {
  elementExecutions: ElementExecution[];
  executedAtEnd: string;
  executedAtStart: string;
  processedInNanos: number;
  result: string;
}
