/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * formula-interpreter API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { DebugFeature } from "./debugFeature";
import type { ExecuteStructuredData } from "./executeStructuredData";

export interface Execute {
  debugFeature: DebugFeature;
  formula: string;
  structuredData: ExecuteStructuredData;
}
