/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * formula-interpreter API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { Range } from "./range";

export interface Input {
  name: string;
  range: Range;
  value: string;
}
