/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * formula-interpreter API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export type SuggestCompletionBody = {
  /** Suggest tokens */
  suggestedFormula: string;
};
