/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * infrastructure API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { ElementExecution } from "./elementExecution";
import type { ExecutionProcessedIn } from "./executionProcessedIn";
import type { ParserExecutionProcessedIn } from "./parserExecutionProcessedIn";

export interface ExecutionResult {
  elementExecutions: ElementExecution[];
  exactProcessedInNanos: number;
  executionProcessedIn: ExecutionProcessedIn;
  parserExecutionProcessedIn?: ParserExecutionProcessedIn;
  result: string;
}
