/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * infrastructure API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { ExecutionProcessedIn } from "./executionProcessedIn";
import type { IntermediateResult } from "./intermediateResult";
import type { ParserExecutionProcessedIn } from "./parserExecutionProcessedIn";

export interface ExecutionResult {
  exactProcessedInNanos: number;
  executionProcessedIn: ExecutionProcessedIn;
  intermediateResults: IntermediateResult[];
  parserExecutionProcessedIn?: ParserExecutionProcessedIn;
  result: string;
}
