/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * infrastructure API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */
import type { PositionedAt } from "./positionedAt";

export interface Input {
  name: string;
  positionedAt: PositionedAt;
  value: string;
}
