/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * infrastructure API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export interface ParserExecutionProcessedIn {
  executedAtEnd: string;
  executedAtStart: string;
  processedInNanos: number;
}
