/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * infrastructure API
 * OpenAPI spec version: 1.0-SNAPSHOT
 */

export type Validate200 = {
  charPositionInLine?: number;
  line?: number;
  msg?: string;
  valid: boolean;
};
